### ISSUE TITLE
laurioninn mischied and elddar forest raid doors

### ISSUE THREAD

**Issue by jandegithub** [brainiac/MQ2EasyFind#100]
```
    laurioninn:
        -   type: ZoneConnection
            switch: 13
            name: 'Plane of Mischief'
            location: [-875.93, -88.46, 27.71]
            targetZone: mischiefplane
        -   type: ZoneConnection
            switch: 16
            name: 'Elddar Forest'
            location: [-854.78, -166.18, 27.71]
            targetZone: elddar   
```

Unsure if targetZone is correct, need to confirm that.
