### ISSUE TITLE
Add connection to Hodstock to Nek and Nek to Hodstock

### ISSUE THREAD

**Issue by burdsjm** [brainiac/MQ2EasyFind#116]
This fixed /travelto toe or other ToB zones from the rest of EQ.

```
    nektulos:
        -   type: ZoneConnection
            location: [-1087, -1020, -23]
            targetZone: hodstock```

     hodstock:
        -   type: Translocator
            name: Torin
            keyword: get on
            targetZone: toe
            expansion: The Outer Brood
        -   type: ZoneConnection
            location: [-1505, 1371, 14]
            targetZone: nektulos
```
