### ISSUE TITLE
Dragonscale Hills zone connection to "Fortress Mechanotus" update location

### ISSUE THREAD

**Issue by Sicprofundus** [brainiac/MQ2EasyFind#17]
this is the zoneconnections.yaml
```yaml
 dragonscale:
        -   type: ZoneConnection
            switch: 6
            targetZone: mechanotus
```
the switch ID 6 is correct, but the location 0,0,0 is incorrect
![image](https://user-images.githubusercontent.com/48923666/135772599-8d842ca8-6b70-4d91-a384-904b7c14161f.png)
![image](https://user-images.githubusercontent.com/48923666/135772602-cf38aa2d-1c37-4306-b005-30afcf9d0554.png)

updating to this fixes it:
```yaml
dragonscale:
        -   type: ZoneConnection
            location: [3734, -2383, 100]
            switch: 6
            targetZone: mechanotus
```
