### ISSUE TITLE
maidentwo -> akhevatwo

### ISSUE THREAD

**Issue by Sicprofundus** [brainiac/MQ2EasyFind#41]
Need location fix from maidentwo -> akhevatwo

```yaml
    maidentwo:
        -   type: ZoneConnection
            location: [-1855, 53, -96]
            targetZone: akhevatwo
```
