### ISSUE TITLE
akhevatwo - > maidentwo

### ISSUE THREAD

**Issue by jandegithub** [brainiac/MQ2EasyFind#42]
```
akhevatwo:
        -   type: ZoneConnection
            location: [-1440.64, 125.44, 22.60]
            targetZone: maidentwo   
```
