### ISSUE TITLE
Muramite Proving Ground -> Riftseeker's Sanctum 

### ISSUE THREAD

**Issue by kaen01** [brainiac/MQ2EasyFind#43]
Working connection:

```
    provinggrounds:
        -   type: ZoneConnection
            location: [-2439, -851.86, -307]
            switch: 13
            targetZone: riftseeker
```
