### ISSUE TITLE
/travelto bloodfalls

### ISSUE THREAD

**Issue by kaen01** [brainiac/MQ2EasyFind#45]
should allow easyfind to find window and travelto to bloodfalls zone

```
    mistmoore:
        -   type: ZoneConnection
            location: [-243.779, 357.845, -149.34]
            switch: 2
            targetZone: bloodfalls
```
