### ISSUE TITLE
From Silyssar, New Chelsith to Zhisza, the Shissar Sanctuary

### ISSUE THREAD

**Issue by kaen01** [brainiac/MQ2EasyFind#49]
The loc pulled from the game is inside the door object, and nav wont mesh the door and an mesh link dont work nor does marking it as walkable area

so gonna need this
```
    Silyssar:
        -   type: ZoneConnection
            location: [1653, -273, -112]
            switch: 1
            targetZone: zhisza
```
