### ISSUE TITLE
added zoneconnections 

### ISSUE THREAD

**Issue by Dazz12** [brainiac/MQ2EasyFind#7]
```yaml
    sseru:
        -   type: ZoneConnection
            location: [1150.54,425.00,80]
            targetZone: Marus Seru
    mseru:

        -   type: ZoneConnection
            location: [-2143.81, -1095.26, -31.15]
            targetZone: Sanctus Seru
    frontiermtns:

        -   type: ZoneConnection
            location: [5982.80, 1441.43, 472.04]
            targetZone: overthere
            identifier: 1

    pojustice:
        -   type: ZoneConnection
            switch: 33
            location: [0.48, 364.99, -5.00]
            targetZone: potranquility
    natimbi:
                    targetZone: nedaria
                -   type: Translocator
                    name: '#Madronoa'
                    keyword: wish to travel
                    targetZone: Qvic
    kodtaz:
        -   type: ZoneConnection
            location: [-638, 2690, -405]
            targetZone: qvic
        -   type: ZoneConnection
            targetZone: natimbi
            identifier: 3
            switch: 5
```
Fixed the following as well:
```yaml
    potranquility:
            targetZone: potimea
            location: [-2172.27, 1193.77, -909.04]
        -   type: ZoneConnection
            switch: 20
        -   type: ZoneConnection
            location: [829,-687,-615]
            targetZone: poair
            switch: 80
        -   type: ZoneConnection
            location: [-1538.79, -11.18, -921.24]
            targetZone: poinnovation
        -   type: ZoneConnection
            location: [11.71, -610.53, -516.26]
            targetZone: pojustice
        -   type: ZoneConnection
            location: [-650, 1186, -931]
            targetZone: postorms
            switch: 15
        -   type: ZoneConnection
            location: [1903, -1110, -887]
            switch: 11
            targetZone: codecay
```
